### ISSUE TITLE
trying to uninstall the package...

### ISSUE THREAD

**Issue by Bressack** [Night-squad/42-nightsquad-package#3]
-- When you uninstall the package:
![Screen Shot 2019-11-27 at 3 35 11 PM](https://user-images.githubusercontent.com/17022349/69732360-caafb480-112b-11ea-8d2b-0cfe1aa1f63d.png)
 -- When you reinstall it just after the first uninstall:
![Screen Shot 2019-11-27 at 3 35 23 PM](https://user-images.githubusercontent.com/17022349/69732424-e31fcf00-112b-11ea-8139-89589ba4edf1.png)
-- and again: 
![Screen Shot 2019-11-27 at 3 35 27 PM](https://user-images.githubusercontent.com/17022349/69732455-f0d55480-112b-11ea-8282-537488e4d8ce.png)
-- aaaaaand agaaaain:
![Screen Shot 2019-11-27 at 3 35 42 PM](https://user-images.githubusercontent.com/17022349/69732495-ffbc0700-112b-11ea-9d7b-eab93d1b6bd0.png)
-- maybe try to "free()" before reload info ;) hahaha

The problem is fix when you relaunch Atom btw.

**Comment by Bressack** [comment]
Packages currently installed on my Atom:
![Screen Shot 2019-11-27 at 3 41 56 PM](https://user-images.githubusercontent.com/17022349/69732741-76f19b00-112c-11ea-93f7-01ac6ca09826.png)

**Comment by SimplySka** [comment]
Fixed on v0.14.4
